---

apiVersion: v1
kind: ImageStream
metadata:
  name: sample-app
  labels:
    app: sample-app

---

apiVersion: v1
kind: BuildConfig
metadata:
  name: sample-app
  labels:
    app: sample-app
    build: sample-app
spec:
  runPolicy: Serial
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'mule4:4.3.0'
  source:
    type: Binary
  output:
    to:
      kind: ImageStreamTag
      name: 'sample-app:latest'
  triggers: []